# Generated by Django 3.1.4 on 2021-12-21 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideshow',
            options={'ordering': ['-article__publish']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='thumbnail',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='slideshow',
            old_name='title',
            new_name='article',
        ),
    ]
